---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install -g npm@latest
install:
  - npm ci
script:
  - npm test
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: npm run now
  on:
    branch: master
    node: lts/*
