---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install -g npm@latest
install:
  - npm ci
script:
  - npm test
deploy:
  provider: script
  script:
    - npm run deploy -- --token=$NOW_TOKEN
    - npm run alias -- --token=$NOW_TOKEN
  on:
    branch: master
